### ISSUE TITLE
Incorrect MAC

### ISSUE THREAD

**Issue by profcav** [cyrildever/ecies-geth#9]
I have generated 10000 crypted messages in python, about 40 of them causing incorrect MAC error in ecies-geth verify
The problem seems to be in this (javascript) part
Tracing one of the "bad" messages, I see in browser.js derive function:

privateKeyA
Uint8Array(32) [173, 116, 187, 135, 227, 174, 143, 83, 228, 120, 90, 115, 136, 82, 14, 197, 182, 177, 42, 120, 127, 253, 0, 138, 230, 234, 51, 144, 13, 195, 60, 243]

publicKeyB
Uint8Array(65) [4, 186, 172, 110, 214, 176, 251, 210, 223, 4, 213, 20, 83, 156, 98, 0, 149, 119, 154, 163, 36, 243, 66, 151, 87, 166, 60, 180, 164, 38, 214, 155, 214, 43, 183, 135, 13, 164, 64, 15, 227, 145, 224, 25, 166, 123, 168, 206, 250, 214, 235, 248, 24, 212, 204, 238, 98, 211, 158, 237, 36, 128, 133, 21, 216]

and the Buffer returned by the function is 31 bytes long instead of 32 bytes

Px 
BN {negative: 0, words: Array(10), length: 10, red: null}

Px.toArray()
(31) [84, 68, 15, 49, 73, 6, 17, 22, 223, 222, 72, 156, 103, 180, 85, 168, 152, 155, 245, 160, 118, 139, 106, 205, 153, 172, 106, 247, 139, 96, 5]

**Comment by cyrildever** [comment]
This is weird: this part of the code fully relies on the [`elliptic`](https://www.npmjs.com/package/elliptic) library.
I updated the dependencies and couldn't be able to reproduce your problem.
Feel free to point me to some test set of yours so we can figure out what's going on if it's still an issue.
